### ISSUE TITLE
Memory issue (file transfer)

### ISSUE THREAD

**Issue by danrobi11** [tof4/lanchat#11]
I've transferred a 900mb file. The lanchat instance on the sender side, took my memory to the roof. 
After the transfer lanchat was using 40% of 16gb RAM.

**Comment by tofudd** [comment]
Partially fixed in da595a47e05fdacd3b834031c0c6f1182a6422f4.
 I tested it with 3 GB file and the memory usage was ~200 MB maximum. However, the speed of file transfer has dropped significantly and the memory remains allocated after its completion.

**Comment by danrobi11** [comment]
My bad. I got busy and I forgot to post the output of the receiver side.
Not sure what happened. I dont recall having an internet disconnection.

```
19:53 -!- Marisa#9301 wants to send you a file Cherry.English.2021.m4v (/accept | /reject)                                                         
19:54 -!- File exchange with Marisa#9301 errored                                                                                                   
19:54 -!- Marisa#9301 disconnected                                                                                                                 
19:55 -!- Marisa#0814 connected  
```

**Comment by tofudd** [comment]
I'm not sure why the disconnection happened but I think it may be related to a memory leak on the sender side.
