### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by ovari** [tof4/lanchat#17]
> I will not continue development of Lanchat after 2.10 release. Any bugs or security issues will not be fixed. Please consider using alternatives.

Could you please suggest [Jami](https://jami.net/) as an alternative on your [README.md](https://github.com/tof4/lanchat#future-updates)?

What do you think?

Thank you

https://jami.net/
https://jami.biz/
https://git.jami.net/savoirfairelinux/jami-project/-/wikis/tutorials/Frequently-Asked-Questions
https://git.jami.net/savoirfairelinux
https://review.jami.net/
https://dl.jami.net/
https://www.transifex.com/savoirfairelinux/jami
https://www.transifex.com/savoirfairelinux/jams-jami-account-management-server/
https://www.transifex.com/savoirfairelinux/jami-website/
https://www.youtube.com/channel/UCIe47cCt_ovwKb2Nfr4nBlw/
https://forum.jami.net/
https://git.jami.net/savoirfairelinux/jami-project/-/wikis/features/All-features-by-client
https://git.jami.net/savoirfairelinux/jami-client-gnome/-/wikis/Changelog
https://savoirfairelinux.com/en

**Comment by tof4** [comment]
Jami looks interesting but is far more complex than Lanchat.
Lanchat was supposed to be simple and convenient for quickly exchanging messages on local networks.

**Comment by ovari** [comment]
Thank you for your response.

Jami works on a local network without any internet, third-party computer, etc. You can have the same Jami account on multiple device and send files between the devices and all the data stays on the LAN.

Thought that if you add Jami to your README.md there would multi-platform (Android, AndroidTV, GNU/Linux, iPhone, iPad, macOS, Windows) alternative as there will not continue development of Lanchat after 2.10 release.

Closing as you have responded and if you chose can update your README.md.

Thank you once again.

**Comment by tof4** [comment]
Thank you. I'll look for more similar apps. Adding *alternatives* section is good idea.

**Comment by ovari** [comment]
1. Should this issue be re-opened?
2. Can Jami be added? https://jami.net/ https://jami.biz/

Thank you once again

**Comment by tof4** [comment]
I'll reopen this issue with changed title.

About Jami. I'll look at it more but I think it's has other purpose and target users than my project.

**Comment by ovari** [comment]
> About Jami. I'll look at it more but I think it's has other purpose and target users than my project.

From your [Features](https://github.com/tof4/lanchat/#features)

> * P2P communication

Jami is peer-to-peer, no server required.

> * Messaging

Jami supports messaging.

> * File transfer

Jami supports file transfers.

> * Encryption

Jami uses TLS 1.3 with a perfect forward secrecy requirement for the negotiated ciphers for calls and file transfers. Messages are encrypted with an RSA key. https://jami.net/help/

> * Automatic connection

If a device is, or become, online Jami automatically connects. See https://jami.net/first-jami-beta-with-swarm-support/

> * Terminal UI

Terminal UI is available at https://github.com/amarok1412/jami-cli

> * Works on Windows, Mac and Linux

Jami works on GNU/Linux, macOS, Windows. In addition Jami works on Android, AndroidTV, iOS (iPhone and iPad)

Seems that the Lanchat features are available with Jami. Is there any other blocker to adding Jami as an alternative to Lanchat?

Thank you

**Comment by tof4** [comment]
>Seems that the Lanchat features are available with Jami. Is there any other blocker to adding Jami as an alternative to Lanchat?

That's not the point. Jami uses DHT and other fancy techniques while Lanchat was made using simpler tools. If someone has already chosen Lanchat and now is looking for alternative Jami will be overkill.

**Comment by tof4** [comment]
I'll create separated issue for alternatives suggestions since it's already quite mess here.
